/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Beholder.gltf 
*/

import React, { useRef, useState, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import beholderGltf from './Beholder.gltf'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(beholderGltf)
  const { actions } = useAnimations(animations, group)
  const [active] = useState(false)

  useEffect(() => {
      actions.Idle.play()
  })

  return (
    <group ref={group} {...props} dispose={null} rotation={[0, 0.5, 0]} scale={active ? 2 : 3}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.Bone} />
          <primitive object={nodes.Bone049} />
          <skinnedMesh name="Beholder" geometry={nodes.Beholder.geometry} material={materials['Material.005']} skeleton={nodes.Beholder.skeleton} />
          <skinnedMesh name="Dentes" geometry={nodes.Dentes.geometry} material={materials['Material.006']} skeleton={nodes.Dentes.skeleton} />
          <skinnedMesh name="Lava" geometry={nodes.Lava.geometry} material={materials['Material.008']} skeleton={nodes.Lava.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(beholderGltf)
