/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Lobsomem.gltf 
*/

import React, { useRef, useState, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import lobsomemGltf from './Lobsomem.gltf'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(lobsomemGltf)
  const { actions } = useAnimations(animations, group)
  const [active] = useState(false)

  useEffect(() => {
      actions.Idle.play()
  })

  return (
    <group ref={group} {...props} dispose={null} rotation={[0, -2, 0]} scale={active ? 2 : 3}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Olhos" geometry={nodes.Olhos.geometry} material={materials['Material.001']} skeleton={nodes.Olhos.skeleton} />
          <skinnedMesh name="Presas" geometry={nodes.Presas.geometry} material={materials.Material} skeleton={nodes.Presas.skeleton} />
          <skinnedMesh name="Lingua" geometry={nodes.Lingua.geometry} material={materials['Material.002']} skeleton={nodes.Lingua.skeleton} />
          <skinnedMesh name="Lobisman" geometry={nodes.Lobisman.geometry} material={materials['Material.002']} skeleton={nodes.Lobisman.skeleton} />
          <skinnedMesh name="Rabo" geometry={nodes.Rabo.geometry} material={materials['Material.002']} skeleton={nodes.Rabo.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(lobsomemGltf)
