/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Apodrecido.gltf 
*/

import React, { useRef, useState, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import apodrecidoglft from './Apodrecido.gltf';

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(apodrecidoglft)
  const { actions } = useAnimations(animations, group)
  const [active] = useState(false)

  useEffect(() => {
    actions.Idle.play()
})
  return (
    <group ref={group} {...props} dispose={null} rotation={[0, -3, 0]} scale={active ? 2 : 3}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.mixamorigHips} />
          <primitive object={nodes.mixamorigtronco_central} />
          <primitive object={nodes.mixamorigtronco_central_r} />
          <primitive object={nodes.mixamorigtronco_r} />
          <primitive object={nodes.mixamorigtronco_traseiro_r} />
          <primitive object={nodes.mixamorigtronco_central_l} />
          <primitive object={nodes.mixamorigtronco_l} />
          <primitive object={nodes.mixamorigtronco_traseiro_l} />
          <skinnedMesh name="Apdrecido_Dentes" geometry={nodes.Apdrecido_Dentes.geometry} material={materials.Material} skeleton={nodes.Apdrecido_Dentes.skeleton} />
          <skinnedMesh name="Apodrecido" geometry={nodes.Apodrecido.geometry} material={materials.Material} skeleton={nodes.Apodrecido.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(apodrecidoglft)
